---
- name: test
  hosts: localhost
  tasks:
  
    - name: Set AWS KEY ID
      set_fact: vault_id="{{ lookup('env','vault') }}"
      delegate_to: 127.0.0.1
    
    - name: vault var
      shell: echo {{vault_id}} |ansible-vault view --ask-vault-pass env_vars/vault.yml
      register: var
    
    - name:
      set_fact:
        decrypted_val
      
    - name:
      set_fact:
        decrypted_val: "{{ (var.stdout_lines | to_json) }}"
        
    - debug:
        msg: "{{ decrypted_val }}"
